### ISSUE TITLE
The application crashes when the task is marked as completed

### ISSUE THREAD

**Issue by SokolovskyMaxim** [iman-salmani/iplan#46]
The screencast shows that when I mark a task completed, the application crashes. At the same time, if you reopen the application, the marked task will move to the completed tasks block, which is true. But an emergency shutdown of the application does not prevent it from working normally

[Запись экрана от 2023-07-06 17-02-44.webm](https://github.com/iman-salmani/iplan/assets/106545001/ecbd8370-b145-4e84-be9a-56ea5d3e4e35)

**Comment by iman-salmani** [comment]
Hi, Thanks for reporting.
Can you run the app in the terminal and send the command output here?
```bash
flatpak run ir.imansalmani.IPlan
```

**Comment by SokolovskyMaxim** [comment]
Yes, sure

flatpak run ir.imansalmani.IPlan
F: Not sharing "/usr/share/fonts" with sandbox: Path "/usr" is reserved by Flatpak
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:1279:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

RUST_BACKTRACE=1 flatpak run ir.imansalmani.IPlan
F: Not sharing "/usr/share/fonts" with sandbox: Path "/usr" is reserved by Flatpak
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:1279:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

RUST_BACKTRACE=full flatpak run ir.imansalmani.IPlan 
F: Not sharing "/usr/share/fonts" with sandbox: Path "/usr" is reserved by Flatpak
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:1279:13
stack backtrace:
   0:     0x5584bfa0625a - <unknown>
   1:     0x5584bfa299cf - <unknown>
   2:     0x5584bfa02d15 - <unknown>
   3:     0x5584bfa06025 - <unknown>
   4:     0x5584bfa076ce - <unknown>
   5:     0x5584bfa07475 - <unknown>
   6:     0x5584bfa07c2e - <unknown>
   7:     0x5584bfa07ae2 - <unknown>
   8:     0x5584bfa066c6 - <unknown>
   9:     0x5584bfa07882 - <unknown>
  10:     0x5584bf60b1a3 - <unknown>
  11:     0x5584bf60b23d - <unknown>
  12:     0x5584bf61a281 - <unknown>
  13:     0x7f40610a79c6 - gtk_widget_activate_action_variant
  14:     0x5584bf73fdb9 - <unknown>
  15:     0x5584bf9e91c6 - <unknown>
  16:     0x7f4060b3b0a4 - <unknown>
  17:     0x7f4060b41442 - g_closure_invoke
  18:     0x7f4060b555c8 - <unknown>
  19:     0x7f4060b5c575 - g_signal_emit_valist
  20:     0x7f4060b5c743 - g_signal_emit
  21:     0x7f4060b45a54 - <unknown>
  22:     0x7f4060b48bf8 - g_object_notify_by_pspec
  23:     0x7f4060f1de9e - gtk_check_button_set_active
  24:     0x7f4060ecb753 - <unknown>
  25:     0x7f4060b4165a - <unknown>
  26:     0x7f4060b5c53f - g_signal_emit_valist
  27:     0x7f4060b5c743 - g_signal_emit
  28:     0x7f4060f7eda3 - <unknown>
  29:     0x7f4060b44a5a - g_cclosure_marshal_VOID__BOXEDv
  30:     0x7f4060b4165a - <unknown>
  31:     0x7f4060b5c53f - g_signal_emit_valist
  32:     0x7f4060b5c743 - g_signal_emit
  33:     0x7f4060f7bac8 - <unknown>
  34:     0x7f4060f7d32b - <unknown>
  35:     0x7f4060f8052a - <unknown>
  36:     0x7f4060f4b0af - <unknown>
  37:     0x7f406109c02a - <unknown>
  38:     0x7f40610a3f18 - <unknown>
  39:     0x7f4060fbb6a2 - <unknown>
  40:     0x7f4060fbbda3 - <unknown>
  41:     0x7f40610b09c0 - <unknown>
  42:     0x7f40612294cc - <unknown>
  43:     0x7f4061255838 - <unknown>
  44:     0x7f4060b4165a - <unknown>
  45:     0x7f4060b5b97e - g_signal_emit_valist
  46:     0x7f4060b5c743 - g_signal_emit
  47:     0x7f40612592e5 - <unknown>
  48:     0x7f4061272916 - <unknown>
  49:     0x7f4060becd49 - g_main_context_dispatch
  50:     0x7f4060bed2a8 - <unknown>
  51:     0x7f4060bed343 - g_main_context_iteration
  52:     0x7f406181835d - g_application_run
  53:     0x5584bf6edfb2 - <unknown>
  54:     0x5584bf793549 - <unknown>
  55:     0x5584bf692923 - <unknown>
  56:     0x5584bf6a6df9 - <unknown>
  57:     0x5584bf9ff1ce - <unknown>
  58:     0x5584bf7960d5 - <unknown>
  59:     0x7f406062954a - <unknown>
  60:     0x7f406062960b - __libc_start_main
  61:     0x5584bf60b7e5 - <unknown>
  62:                0x0 - <unknown>

**Comment by SokolovskyMaxim** [comment]
Yes, it was worth mentioning that I use Russian, and it is clearly different from ASCII
